os: linux
dist: bionic

install:
  - wget -qO- https://cmake.org/files/v3.17/cmake-3.17.0-Linux-x86_64.tar.gz | tar xvz

language: cpp
compiler:
  - gcc

before_script:
  - export CC=gcc-7
  - export CXX=g++-7

addons:
  sonarcloud:
    organization: "timkante"
    token:
      secure: "KXBUdmSUgs/SCLy0U1iZJY1xBpkt0FJdH+lAC6fe1WO/iiHfFbbu+Sx9GA1ml9XaK1W3kXpPvqSmFog2q+dGl4j+HKrxLJuOgq6T0PborBovWKkWNcRxsa+H4fqhh+kgSzUZNABofDSZl5fXzibNTD3yWW+j4OWjvBAAZXKOVSiPj2EoVAWjX9prcf5LPqUs50yrroO5U2KIanrzFaOn/CeGA+HceC0SY5izuSJQJe8AoiVOuMvU1BQXa0pRIGFsiIc3NgUmATP5KdWSbeEAYCX9aKTLwKf+7pKZkjx/LLyuQDY0MIZ2xDUaX0pE7Xp7GGMzptn3UHBZc5K9lLpYPXZBouYa5I3cZtuOSHm/uSORwfpPXCdIBdjMAqnx9qxaiiuRNBk/iSrfLsE+W8NnQ+QRlOpYvnEsAp/fgHXLiIK7uX1kNhS1EjZtnOx46Jc52yWQ61x6DuXcPL0EGVnRucKjFuzXQZQiuF/ZT6UzYF1TPagW69xHtq2oHcDvPRiVuzjA+xSLSWBUBLgoA6biSO9H3mglJQGd093EaZAGKBxYzVjS/7j6Yy+dfQiamvwShJ6XkCwbioFJWtN+mKX3Z6bFfZWpKmvhojZ2zTEvUR2Xe8rWfk1he0cNBEQhLl/n+/2vusAMpJH2+i3/SIG2dhxE6nFAFcU0ut4mFCOBEeY=" # encrypted value of your token

script:
  - mkdir cmake-build-debug
  - mkdir coverage
  - cd cmake-build-debug
  - ../cmake-3.17.0-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Debug ./../
  - cd ..
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output ./cmake-3.17.0-Linux-x86_64/bin/cmake --build ./cmake-build-debug/ --target bibParserTests -- -j 6
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
  - ./cmake-build-debug/test/bibParserTests
  - cd ./coverage
  - GCOV_FILES=$(find ./../cmake-build-debug -path ./../cmake-build-debug/dependencies -prune -o -name "*.gcno" -print)
  - echo $GCOV_FILES
  - gcov --version
  - gcov $GCOV_FILES